pipeline:
    name: CI - Compose
    identifier: CI_Compose
    allowStageExecutions: false
    projectIdentifier: Scala
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.Github
                repoName: geotrellis
                build: <+input>
    stages:
        - stage:
              name: Build and Test
              identifier: Build_and_Test
              type: CI
              spec:
                  cloneCodebase: true
                  sharedPaths:
                      - /var/run
                      - /var/lib/docker
                      - /usr/local/src
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-builds
                          automountServiceAccountToken: false
                  serviceDependencies:
                      - identifier: DiND
                        name: DiND
                        type: Service
                        spec:
                            connectorRef: org.Dockerhub
                            image: docker:dind
                            privileged: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Check DiND
                                identifier: Check_DiND
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: docker:dind
                                    shell: Sh
                                    command: |-
                                        while ! docker ps ;do
                                            echo "Docker not available yet"
                                        done
                                        echo "Docker service is up"
                                        docker ps 
                          - step:
                                type: Run
                                name: Unzip Rasters
                                identifier: Unzip_Rasters
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: bash:latest
                                    shell: Bash
                                    command: |-
                                        cd raster/data; 
                                        unzip geotiff-test-files.zip
                          - step:
                                type: Run
                                name: Run Tests
                                identifier: Run_Tests
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: docker/compose:1.29.2
                                    shell: Sh
                                    command: |-
                                        ls
                                        docker-compose -v
                                        docker-compose -f docker-compose.yaml up test
                                    privileged: true
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    envVariables:
                                        SCALA_VERSION: 2.13.7
